version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - echo pre-build
  build:
    commands:
    - echo Build-started
    - mvn  package
  post_build:
    commands:
    - echo post-build
artifacts:
  files:
  - target/employee-service-0.0.1-SNAPSHOT.jar